# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "eiio"
license = "MIT"
licenselink = "https://github.com/leonhe/hugo_eiio/master/LICENSE.md"
description = "personal blog&project theme"
homepage = "https://hii8.com/"
tags = ["blog"]
features = ["blog", "project"]
min_version = 0.17

[author]
  name = "Leon He"
  homepage = "https://hii8.com"

# If porting an existing theme
[original]
  name = "hugo_eiio"
  homepage = "https://hii8.com"
  repo = "https://github.com/leonhe/hugo_eiio"
