# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Eiio"
license = "MIT"
licenselink = "https://github.com/leonhe/hugo_eiio/master/LICENSE.md"
description = "Eiio theme"
homepage = "https://feiio.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.17

[author]
  name = "Leon He"
  homepage = "http://feiio.com"

# If porting an existing theme
[original]
  name = "origin"
  homepage = "https://feiio.com"
  repo = "master"
